hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000  # Hystrix的超时时间改为5秒
      circuitBreaker:
        requestVolumeThreshold: 20  # 当在配置时间窗口内达到此数量的失败后，进行短路。默认20个
        sleepWindowInMilliseconds: 10s #短路多久以后开始尝试是否恢复，默认5s
        errorThresholdPercentage: 50% #出错百分比阈值，当达到此阈值后，开始短路。默认50%
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 10 #调用线程允许请求HystrixCommand.GetFallback()的最大数量，默认10。超出时将会有异常抛出，注意：该项配置对于THREAD隔离模式也起作用
  threadpool:
    default:
      coreSize: 30 #线程池核心线程数,默认为10
      maxQueueSize: -1 #最大排队长度。默认-1，使用SynchronousQueue。其他值则使用 LinkedBlockingQueue。如果要从-1换成其他值则需重启，即该值不能动态调整，若要动态调整，需要使用到下边这个配置


pay:
  alipay:
    partner: test



  weixin:



  unionpay: