server:
  port: 8882

mamahao:
  data:
    dataSource:
      dataSourceItems:
        - master: true
          name: master
          url: jdbc:mysql://172.28.1.6:3306/demo_person?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true
          username: root
          password: mamahao
        - master: false
          name: slave
          url: jdbc:mysql://172.28.1.6:3306/demo_person?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true
          username: root
          password: mamahao